---
- name: Backup Configurations
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    
  tasks:
    - name: Creates backup directory
      file:
        path: "prechecks/{{ inventory_hostname }}"
        state: directory
      run_once: true
      check_mode: true
      register: dir_name
      
    - name: Remove existing file if it exists
      file:
        path: "precheck_{{ inventory_hostname }}.txt"
        state: absent

    - name: Creates file
      file:
        path: "precheck_{{ inventory_hostname }}.txt"
        state: touch
