---
- name: Backup Configurations
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    
  tasks:
    - name: Creates backup directory
      file:
        path: "prechecks/{{ inventory_hostname }}"
        state: directory
      run_once: true
      check_mode: true
      register: dir_name
      
    - debug: var=dir_name