---
- name: Validate Cisco IOS Version
  hosts: all
  gather_facts: no
  vars:
    expected_ios_version: ""  # Expected input OS version

  tasks:
    - name: Gather current OS version
      cisco.ios.ios_facts:
      register: device_facts
      vars:
        ansible_network_os: ios
      connection: network_cli
      become: yes
      become_method: enable

    - name: Check current image
      debug:
        msg: "Current OS image: {{ device_facts.ansible_facts.ansible_net_image }}"

    - name: Set current version from ansible_net_image
      set_fact:
        current_ios_version: "{{ device_facts.ansible_facts.ansible_net_image | regex_replace('^.*?(cat9k_iosxe.*?\\.bin)', '\\1') }}"

    - name: Extract current OS version
      debug:
        msg: "Extracted current OS version: {{ current_ios_version }}"

    - name: Check if OS version matches the expected version
      fail:
        msg: "OS version matches the expected version. No further actions required."
      when: current_ios_version == expected_ios_version

    - name: OS version mismatch - success message
      debug:
        msg: "OS version does not match the expected version. Proceeding with further actions."
      when: current_ios_version != expected_ios_version
