---
- name: Ping Values Transformation
  hosts: devices
  gather_facts: no
  strategy: linear
  tasks:
    - import_role:
        name: ping_transform

- name: Prestaging
  hosts: devices
  gather_facts: no
  connection: network_cli
  strategy: free
  tasks:
    - import_role:
        name: prestaging
    
