---
- name: Validate Cisco IOS XE Version
  hosts: all
  gather_facts: no
  vars:
    expected_ios_version: "cat9k_iosxe.17.09.04a.SPA.bin"  # Expected version from your input

  tasks:
    - name: Gather current IOS version
      cisco.ios.ios_facts:
      register: device_facts

    - name: Debug device facts
      debug:
        var: device_facts

    - name: Debug current IOS image
      debug:
        msg: "Current IOS image: {{ device_facts.ansible_facts.ansible_net_image }}"

    - name: Set current IOS version from ansible_net_image
      set_fact:
        current_ios_version: "{{ device_facts.ansible_facts.ansible_net_image | regex_replace('(?<=:)(cat9k_iosxe.*\\.bin)', '\\1') }}"

    - name: Debug current IOS version
      debug:
        msg: "Extracted current IOS version: {{ current_ios_version }}"

    - name: Check if IOS version matches the expected version
      fail:
        msg: "IOS version matches the expected version. No further actions required."
      when: current_ios_version == expected_ios_version

    - name: IOS version mismatch - success message
      debug:
        msg: "IOS version does not match the expected version. Proceeding with further actions."
      when: current_ios_version != expected_ios_version

