- name: SHOW VERSION TEST
  hosts: all
  gather_facts: no

  tasks:
    - name: GET SOFTWARE VERSION
      ios_command:
        commands: show version
        wait_for: result[0] contains IOS
      register: ios_version
      vars:
        ansible_network_os: ios
      connection: network_cli
      become: yes
      become_method: enable

    - name: SHOW SOFTWARE VERSION
      debug:
        msg: "{{ ios_version.stdout_lines[0][0] }}"
