---
- name: Validate Cisco IOS XE Version
  hosts: all
  gather_facts: no
  vars:
    expected_ios_version: "16.9.4"  # Replace with the version you expect

  tasks:
    - name: Gather current IOS version
      cisco.ios.ios_facts:
      register: device_facts
      vars:
        ansible_network_os: ios
      connection: network_cli
      become: yes
      become_method: enable

    - name: Check if IOS version matches the expected version
      debug:
        msg: "Current IOS version: {{ device_facts.ansible_net_version }}"

    - name: Validate IOS version
      fail:
        msg: "IOS version matches the expected version. No further actions required."
      when: device_facts.ansible_net_version == expected_ios_version

    - name: IOS version mismatch - proceed with further actions
      debug:
        msg: "IOS version does not match the expected version. Proceeding with further actions."
      when: device_facts.ansible_net_version != expected_ios_version
