---
- name: Validate Cisco IOS XE Version
  hosts: all
  gather_facts: no
  vars:
    expected_ios_version: "16.9.4"  # Replace with the version you expect

  tasks:
    - name: Gather current IOS version
      cisco.ios.ios_facts:
      register: device_facts
      vars:
        ansible_network_os: ios
      connection: network_cli
      become: yes
      become_method: enable

    - name: Debug device facts
      debug:
        var: device_facts
