---
- name: Find out playbooks runtime path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout

- name: List contents of runtime path
  shell: "ls {{ playbook_path_output.stdout }}"
  register: ls_output
- debug: var=ls_output

- debug: var=prechecks_{{ inventory_hostname }}
