---
- name: Fetch volume names
  include_role:
    name: utils/volume_names

- name: Calculate Free Storage
  include_role:
    name: utils/calculate_free_storage

- name: Gather only hardware facts
  cisco.ios.ios_facts:
    gather_subset:
      - hardware

- block:
    - block:
        - name: Preparing primary flash variable...
          debug:
            msg: "device_primary_flash_{{ inventory_hostname }}"
          register: temp

        - name: Preparing primary flash variable...
          debug:
            msg: "{{ temp.msg | replace('-', '_') }}"
          register: device_primary_flash_variable

        - name: Assign primary flash name to artifacts
          ansible.builtin.set_stats:
            data:
              "{{device_primary_flash_variable.msg}}": "{{device_primary_flash}}"

    - name: Assert that IOS device has free memory in primary memory
      assert:
        that:
          - "'ios' == ansible_net_system"
          - 1000 < primary_flash_memfree_mb | default('1001') | int
        success_msg: Device is in healthy state.
        fail_msg: Device should be manually verified.
      ignore_errors: true
  when: device_primary_flash is defined

- block:
    - block:
        - name: Preparing secondary flash variable...
          debug:
            msg: "device_secondary_flash_{{ inventory_hostname }}"
          register: temp

        - name: Preparing secondary flash variable...
          debug:
            msg: "{{ temp.msg | replace('-', '_') }}"
          register: device_secondary_flash_variable

        - name: Assign secondary flash name to artifacts
          ansible.builtin.set_stats:
            data:
              "{{device_secondary_flash_variable.msg}}": "{{device_secondary_flash}}"

    - name: Assert that IOS device has free memory in secondary memory
      assert:
        that:
          - "'ios' == ansible_net_system"
          - 1000 < secondary_flash_memfree_mb | default('1001') | int
        success_msg: Device is in healthy state.
        fail_msg: Device should be manually verified.
  when: device_secondary_flash is defined
