---
# - name: Find out playbooks runtime path
#   shell: pwd
#   register: playbook_path_output
# - debug: var=playbook_path_output.stdout

# - name: List contents of runtime path
#   shell: "ls {{ playbook_path_output.stdout }}"
#   register: ls_output
# - debug: var=ls_output

- name: Preparing Prechecks file variable...
  debug:
    msg: "prechecks_{{ inventory_hostname }}"
  register: temp

- name: Preparing Prechecks file variable....
  debug:
    msg: "{{ temp.msg | replace('-', '_') }}"
  register: file

- name: Setting fact for device variable
  set_fact:  
    file_name="{{ file.msg }}"

- debug: 
    var: "file_name"

- debug: 
    msg: "{{ lookup('vars', file_name) }}"