---
- block:
  - name: Device primary volume name
    ios_command:
      commands:
        - "dir"
    register: dir_output

  - name: "Determine if primary volume name is {{ item }}"
    set_fact: device_primary_flash="{{item}}"
    when: dir_output['stdout'][0][:40].find(' {{item}}:') != -1
    loop: "{{ primary_flash_names.ios }}"
    
  - name: debug primary flash name
    debug: var="device_primary_flash"
    when: device_primary_flash is defined

- block: 
  - name: Device secondary volume name
    ios_command:
      commands:
        - "show file systems"
    register: file_systems_output

  - name: "Determine if secondary volume name is {{ item }}"
    set_fact: device_secondary_flash="{{item}}"
    when: file_systems_output['stdout'][0].find(' {{item}}:') != -1
    loop: "{{ secondary_flash_names.ios }}"

  - name: debug secondary flash
    debug: var="device_secondary_flash"
    when: device_secondary_flash is defined