---
- name: Verify Current Version
  hosts: all
  gather_facts: no

  tasks:
    - name: GET SOFTWARE VERSION
      ios_command:
        commands: show version
        wait_for: result[0] contains IOS
      register: ios_version
      vars:
        ansible_network_os: ios
      connection: network_cli
      become: yes
      become_method: enable
      when: "{{ device_os }} is ios"

    - name: GET SOFTWARE VERSION
      nxos_command:
        commands: show version
      register: nxos_version
      vars:
        ansible_network_os: nxos
      connection: network_cli
      become: yes
      become_method: enable
      when: "{{ device_os }} is nxos"
