---
- name: Verify Current Version
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather facts to check IOS version
      ios_facts:
        gather_subset:
          - min
          - hardware
      register: output
      connection: network_cli
      vars:
        ansible_network_os: ios

    - name: Show installed boot image version
      debug: msg="{{ ansible_net_image }}"
      when: output is defined