---
- name: Wait until the device becomes reachable
  ansible.builtin.wait_for_connection:
    timeout: 3600

- name: Gather facts to check IOS version
  ios_facts:
    gather_subset:
      - min
      - hardware
  register: output

- name: Show installed boot image version
  debug: msg="{{ ansible_net_image }}"
  when: output is defined

- name: Assert That It is Running The Desired boot Image
  assert:
    that:
      - expected_os_version in ansible_net_image
    success_msg: Device is running target image.
    fail_msg: Device is not running target image.
  ignore_errors: true