---
- debug: var="ping.msg['{{ inventory_hostname }}']"
  register: current_ping_values
  
- debug: msg="{{ current_ping_values | get_rsync_server }}"
  register: rsync_host

- debug: var="rsync_host.msg"

- name: Save running config before starting
  ios_config:
    save_when: always

- name: debug primary flash name
  debug: var="device_primary_flash"
  when: device_primary_flash is defined

- name: debug secondary flash
  debug: var="device_secondary_flash"
  when: device_secondary_flash is defined

# Remove inactive software image

# Remote copy of image to primary flash

# copy image from primary to secondary

# Get md5 of IOS file in secondary flash

# Assert that MD5 of secondary flash IOS file Is Correct
