---
- name: Gather only hardware facts
  cisco.ios.ios_facts:
    gather_subset:
      - hardware

- name: Gather CPU usage and free memory
  ios_command:
    commands:
      - "show processes cpu"
  register: output

- name: Assert that IOS device has optimal CPU percentage
  assert:
    that:
      - 85 > "item.split()[-1] | replace('%', '')" | int
    success_msg: Device is in healthy state.
    fail_msg: Device should be manually verified.
  loop: "{{ output['stdout'][0] | regex_replace('\n', '|') | split('|') }}"
  when: "'five minutes:' in item"