---
- name: Find closest rsync server for devices
  vars: 
    devices: []
  set_fact:
    temp: "rsync_host_{{item}}"
  set_fact: 
    devices: "{{ devices|default([]) + [ temp ] }}"
  loop: "{{groups['devices']}}"