---
- name: Ping devices tasks
  include_tasks: ping.yml
  vars: 
    device: "{{item}}"
  loop: "{{groups['devices']}}"

- name: Preparing artifact
  ansible.builtin.set_stats:
    data:
      "ping_values": "{{ ping_values|default([]) + [ item ] }}"
  loop: "{{ lookup('list', ping) }}"
