---
- name: Find closest rsync server for devices
  vars: 
    devices: []
  set_fact:
    current_device: "{{ item | replace('-', '_')}}"
    devices: "{{ devices|default([]) + [ current_device ] }}"
  loop: "{{groups['devices']}}"