---
- name: Find closest rsync server for devices
  set_fact:
    "current_device_{{device_number}}": "{{ item | replace('-', '_')}}"
    devices: "{{ devices|default([]) + [ device_number ] }}"
    device_number: "{{ device_number | int + 1 }}"
  loop: "{{groups['devices']}}"

- debug: var="devices"
  

