---
- name: Find closest rsync server for devices
  set_fact:
    "current_device_{{device_number}}": "{{ item | replace('-', '_')}}"
    device_number: "{{ device_number | int + 1 }}"
  loop: "{{groups['devices']}}"

- name: Checking
  debug: var="current_device_0"

- name: Checking
  debug: var="current_device_1"
  
  

