---
- name: Find closest rsync server for devices
  vars: 
    devices: []
  set_fact:
    current_device: "{{ item | replace('-', '_')}}" + "{{device_number}}"
    device_number: "{{ device_number | int + 1 }}"
  loop: "{{groups['devices']}}"