---
- name: Find closest rsync server for devices
  vars: 
    current_device: ''
  set_fact:
    current_device: "{{ item | replace('-', '_')}}"
  debug: var="current_device"
  loop: "{{groups['devices']}}"