---
- name: Prepare device list
  set_fact:
    devices: "{{ devices|default([]) + [ {'device': item, 'time': '10000'} ] }}"
  loop: "{{groups['devices']}}"

- name: Ping devices tasks
  include_tasks: ping.yml
  vars: 
    device: "{{item.device}}"
  loop: "{{devices}}"
