---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"
# - debug: var="inventory_hostname"
# - debug: var="cur_item"

- name: test
  set_fact: 
    "{{device_var}}#{{host_var}}": "20"