---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"

- name: Store ping values
  ansible.builtin.set_stats:
    data:
      "{{host_var}}_ping_{{device_var}}": "20"