---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"

- name: Intermediate Processing...
  set_fact: str={{ping_output['stdout_lines'][1][ping_output['stdout_lines'][1].find('time'):]}}

- name: Intermediate Processing...
  set_fact: ping_val={{str[5:str.find(' ')]}}

- name: Store ping values
  set_fact:
    ping_values: "{{ ping_values|default([]) + [ {'destination': device, 'source': inventory_hostname, 'value': ping_val | float } ] }}"
    

- name: test
  set_fact:
    cur: "ping_{{device}}"

- name: test
  ansible.builtin.set_stats:
      data:
        "{{cur}}": "{{ cur|default([]) + [ {inventory_hostname: ping_val | float} ] }}"

# https://www.freekb.net/Article?id=4636#:~:text=Here%20is%20how%20you%20can,%3A%20var%3A%20food%20...