---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"

- name: Store ping values
  ansible.builtin.set_stats:
    data:
      "ping": "{{ ping|default([]) + [ {'x': device_var, 'y': host_var, 'z': '0'} } ] }}"
