---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"

- name: Store ping values
  set_fact:
    ping_values: "{{ ping_values|default([]) + [ {'destination': device, 'source': inventory_hostname, 'value': '0'} ] }}"
    
