---
- name: Ping devices
  shell: "ping -c 1 -w 3 {{ device }}"
  register: ping_output

- debug: var="ping_output"

- name: Store ping values
  set_fact:
    ping: "{{ ping|default([]) + [ {'destination': device_var, 'source': host_var, 'value': '0'} ] }}"
